src/Redes/SivelBundle/Entity/UnidadMedida.php
<?php

namespace Redes\SivelBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * UnidadMedida
 *
 * @ORM\Table(name="unidad_medida")
 * @ORM\Entity
 */
class UnidadMedida
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="bigint", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nombre_unidad", type="text", length=65535, nullable=false)
     */
    private $nombreUnidad;



    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nombreUnidad
     *
     * @param string $nombreUnidad
     * @return UnidadMedida
     */
    public function setNombreUnidad($nombreUnidad)
    {
        $this->nombreUnidad = $nombreUnidad;

        return $this;
    }

    /**
     * Get nombreUnidad
     *
     * @return string 
     */
    public function getNombreUnidad()
    {
        return $this->nombreUnidad;
    }

        public function getNombrePersona()
    {
        return $this->nombreUnidad;
    }
}

src/Redes/SivelBundle/Resources/views/Template/cooperantes.html.twig
<!-- team -->
<h3 class="text-center  wowload fadeInUp">Cooperantes</h3>
<div class="row grid team  wowload fadeInUpBig">  
  <div class=" col-sm-3 col-xs-6">
  <figure class="effect-chico">
        <img src="{{ asset('images/team/1.jpg') }}" class="img-responsive" /><figcaption><p><a href="#"><b>Fundacion REDES</b></a></p></figcaption>
  </figure>
</div>
  <div class=" col-sm-3 col-xs-6">
  <figure class="effect-chico">
        <img src="{{ asset('images/team/2.jpg') }}" class="img-responsive" /><figcaption><p><a href="#"><b>Diputacion de Zaragoza</b></a></p></figcaption>
  </figure>
</div>
  <div class=" col-sm-3 col-xs-6">
  <figure class="effect-chico">
        <img src="{{ asset('images/team/3.jpg') }}" class="img-responsive" /><figcaption><p><a href="#"><b>Manos Unidas</b></a></p></figcaption>
  </figure>
</div>
  <div class=" col-sm-3 col-xs-6">
  <figure class="effect-chico">
        <img src="{{ asset('images/team/4.jpg') }}" class="img-responsive" /><figcaption><p><a href="#"><b>Ayuntamiento de Majadahonda</b></a></p></figcaption>
  </figure>
</div>
<!-- team -->
</div>
<div class="row grid team  wowload fadeInUpBig">  
  <div class=" col-sm-3 col-xs-6">
  <figure class="effect-chico">
        <img src="{{ asset('images/team/5.jpg') }}" class="img-responsive" /><figcaption><p><a href="#"><b>Ayuntamiento de Alcobendas</b></a></p></figcaption>
  </figure>
</div>
  <div class=" col-sm-3 col-xs-6">
  <figure class="effect-chico">
        <img src="{{ asset('images/team/6.jpg') }}" class="img-responsive" /><figcaption><p><a href="#"><b>Ayuntamiento de Oviedo</b></a></p></figcaption>
  </figure>
</div>
  <div class=" col-sm-3 col-xs-6">
  <figure class="effect-chico">
        <img src="{{ asset('images/team/7.jpg') }}" class="img-responsive" /><figcaption><p><a href="#"><b>Ayuntamiento de Sabadell</b></a></p></figcaption>
  </figure>
</div>
  <div class=" col-sm-3 col-xs-6">
  <figure class="effect-chico">
        <img src="{{ asset('images/team/8.jpg') }}" class="img-responsive" /><figcaption><p><a href="#"><b>Ayuntamiento de Onda</b></a></p></figcaption>
  </figure>
</div>
<!-- team -->
</div>
<div class="row grid team  wowload fadeInUpBig">  
<div class=" col-sm-3 col-xs-6">
</div>
  <div class=" col-sm-3 col-xs-6">
  <figure class="effect-chico">
        <img src="{{ asset('images/team/9.jpg') }}" class="img-responsive" /><figcaption><p><a href="#"><b>Ayuntamiento de Derdanyola del Valle</b></a></p></figcaption>
  </figure>
</div>
  <div class=" col-sm-3 col-xs-6">
  <figure class="effect-chico">
        <img src="{{ asset('images/team/10.jpg') }}" class="img-responsive" /><figcaption><p><a href="#"><b>Ayuntamiento de la Roca del Valle</b></a></p></figcaption>
  </figure>
</div>
<div class=" col-sm-3 col-xs-6">
</div>
<!-- team -->
</div>

src/Redes/SivelBundle/Resources/views/Template/estadisticas.html.twig
<h3 class="text-center  wowload fadeInUp">Estadisticas</h3>
<!-- About Starts -->
<div class="highlight-info">
<div class="overlay spacer">
<div class="container">
<div class="row text-center  wowload fadeInDownBig">
  <div class="col-sm-3 col-xs-6">
  <i class="fa fa-female  fa-5x"></i><h4>{% for d in mujer %}{{ d.1 }}{% endfor %} Miembras</h4>
  </div>
  <div class="col-sm-3 col-xs-6">
  <i class="fa fa-child fa-5x"></i><h4>{% for d in hombre %}{{ d.1 }}{% endfor %} Miembros</h4>
  </div>
  <div class="col-sm-3 col-xs-6">
  <i class="fa fa-cubes  fa-5x"></i><h4>{% for d in producto %}{{ d.1 }}{% endfor %} Productos</h4>
  </div>
  <div class="col-sm-3 col-xs-6">
  <i class="fa fa-cutlery  fa-5x"></i><h4>{% for d in servicio %}{{ d.1 }}{% endfor %} Servicios registrados</h4>
  </div>
</div>
</div>
</div>
</div>
<!-- About Ends -->

src/Redes/SivelBundle/Resources/views/Template/experiencia.html.twig
<div id="partners" class="container spacer ">
  <h2 class="text-center  wowload fadeInUp">Comentarios de beneficiarios de la plataforma</h2>
  <div class="clearfix">
    <div class="col-sm-6 partners  wowload fadeInLeft">
         <img src="images/partners/1.jpg" alt="partners">
         <img src="images/partners/2.jpg" alt="partners">
         <img src="images/partners/3.jpg" alt="partners">
         <img src="images/partners/4.jpg" alt="partners">
    </div>
    <div class="col-sm-6">
    <div id="carousel-testimonials" class="carousel slide testimonails  wowload fadeInRight" data-ride="carousel">
    <div class="carousel-inner">  
      <div class="item active animated bounceInRight row">
      <div class="animated slideInLeft col-xs-2"><img alt="portfolio" src="images/team/1.jpg" width="100" class="img-circle img-responsive"></div>
      <div  class="col-xs-10">
      <p> I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. </p>      
      <span>Angel Smith - <b>eshop Canada</b></span>
      </div>
      </div>
      <div class="item  animated bounceInRight row">
      <div class="animated slideInLeft col-xs-2"><img alt="portfolio" src="images/team/2.jpg" width="100" class="img-circle img-responsive"></div>
      <div  class="col-xs-10">
      <p>No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful.</p>
      <span>John Partic - <b>Crazy Pixel</b></span>
      </div>
      </div>
      <div class="item  animated bounceInRight row">
      <div class="animated slideInLeft  col-xs-2"><img alt="portfolio" src="images/team/3.jpg" width="100" class="img-circle img-responsive"></div>
      <div  class="col-xs-10">
      <p>On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue.</p>
      <span>Harris David - <b>Jet London</b></span>
      </div>
      </div>
  </div>
   <!-- Indicators -->
    <ol class="carousel-indicators">
    <li data-target="#carousel-testimonials" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-testimonials" data-slide-to="1"></li>
    <li data-target="#carousel-testimonials" data-slide-to="2"></li>
    </ol>
    <!-- Indicators -->
  </div>
    </div>
  </div>

src/Redes/SivelBundle/Resources/views/Template/footer.html.twig
<div id="contact" class="spacer">
<!--Contact Starts-->
 <div id="Map" class="olMap" style="width: 100%; height: 600px; margin: 0;"> </div>

</div>
<!--Contact Ends-->

<!-- Footer Starts -->
<div class="footer text-center spacer">
<p class="wowload flipInX">
  <a href="http://www.facebook.com/fundaredes"><i class="fa fa-facebook fa-2x"></i></a> 
  <a href="http://www.youtube.com/user/RedesFundacion?sub_confirmation=1"><i class="fa fa-youtube fa-2x"></i></a> 
  <a href="http://twitter.com/fundredes"><i class="fa fa-twitter fa-2x"></i></a> 
  <a href="http://redes.org.sv/rss"><i class="fa fa-rss fa-2x"></i></a> 
</p>
<p><b>Fundación Salvadoreña para la Reconstrucción y el Desarrollo – REDES</b><br/>
Los contenidos de este sitio web están bajo una<b> <a href="http://creativecommons.org/licenses/by-nc-nd/3.0/deed.es_CO"> Licencia Creative Commons BY-NC-ND </a></b></p>
</div>
<!-- # Footer Ends -->
<a href="#home" class="gototop "><i class="fa fa-angle-up  fa-3x"></i></a>

<!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- Controls for the borderless lightbox -->
    <h3 class="title">Title</h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <!-- The modal dialog, which will be used to wrap the lightbox content -->    
</div>

<script src="{{ asset('assets/js/osm/OpenLayers-2.13.1/OpenLayers.js') }}"></script>
<script>
    var lat            = 13.697911;
    var lon            = -89.218846;
    var zoom           = 8;
    var icoPng       = '{{ asset('images/icoMap.png') }}';
    
    map = new OpenLayers.Map("Map");
    map.addLayer(new OpenLayers.Layer.OSM());
    
    epsg4326 =  new OpenLayers.Projection("EPSG:4326"); //WGS 1984 projection
    projectTo = map.getProjectionObject(); //The map projection (Spherical Mercator)
   
    var lonLat = new OpenLayers.LonLat( lon ,lat ).transform(epsg4326, projectTo);
    map.setCenter (lonLat, zoom);

    var vectorLayer = new OpenLayers.Layer.Vector("Overlay");
    
    // Define markers as "features" of the vector layer:
    
    {% for d in all %}
      var feature = new OpenLayers.Feature.Vector(
            new OpenLayers.Geometry.Point( {{ d.longitudPersona }}, {{ d.latitudPersona }} ).transform(epsg4326, projectTo),
            {description:'<a href="#" ><b>{{ d.nombrePersona }} </b></a><br/>'} ,
            {externalGraphic: icoPng, graphicHeight: 30, graphicWidth: 28, graphicXOffset:-12, graphicYOffset:-25  }
        );
        vectorLayer.addFeatures(feature);
    {% endfor %}

    map.addLayer(vectorLayer); 
    
    //Add a selector control to the vectorLayer with popup functions
    var controls = {
      selector: new OpenLayers.Control.SelectFeature(vectorLayer, { onSelect: createPopup, onUnselect: destroyPopup })
    };

    function createPopup(feature) {
      feature.popup = new OpenLayers.Popup.FramedCloud("pop",
          feature.geometry.getBounds().getCenterLonLat(),
          null,
          '<div class="markerContent">'+feature.attributes.description+'</div>',
          null,
          true,
          function() { controls['selector'].unselectAll(); }
      );
      //feature.popup.closeOnMove = true;
      map.addPopup(feature.popup);
    }

    function destroyPopup(feature) {
      feature.popup.destroy();
      feature.popup = null;
    }
    
    map.addControl(controls['selector']);
    controls['selector'].activate();
      
  </script>

src/Redes/SivelBundle/Resources/views/Template/head.html.twig
<!-- Header Starts -->
<div class="navbar-wrapper">
      <div class="container">

        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation" id="top-nav">
          <div class="container">
            <div class="navbar-header">
              <!-- Logo Starts -->
              <a class="navbar-brand" href="#home"><img src="{{ asset('images/logo.png') }}" alt="logo"></a>
              <!-- #Logo Ends -->


              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>

            </div>


            <!-- Nav Starts -->
            <div class="navbar-collapse  collapse">
              <ul class="nav navbar-nav navbar-right scroll">
                 <li class="active"><a href="#home">Inicio</a></li>
                 <li ><a href="#about">Sobre la plataforma</a></li>
                 <li ><a href="#works">Socias y Socios</a></li>
                 <li ><a href="#partners">Cooperantes</a></li>
                 <li ><a href="#contact">Solicitar productos o servicios</a></li>
              </ul>
            </div>
            <!-- #Nav Ends -->

          </div>
        </div>

      </div>
    </div>
<!-- #Header Starts -->
<div id="home">
<!-- Slider Starts -->
<div id="myCarousel" class="carousel slide banner-slider animated bounceInDown" data-ride="carousel">     
      <div class="carousel-inner">
        <!-- Item 1 -->
        <div class="item active">
          <img src="{{ asset('images/back1.png') }}" alt="banner">
        </div>
        <!-- #Item 1 -->

        <!-- Item 1 -->
        <div class="item">
          <img src="{{ asset('images/back2.png') }}" alt="banner">
        </div>
        <!-- #Item 1 -->

        <!-- Item 1 -->
        <div class="item">
          <img src="{{ asset('images/back3.png') }}" alt="banner">
        </div>
        <!-- #Item 1 -->

        <!-- Item 1 -->
        <div class="item">
          <img src="{{ asset('images/back4.png') }}" alt="banner">
        </div>
        <!-- #Item 1 -->
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon-chevron-left"><i class="fa fa-angle-left"></i></span></a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon-chevron-right"><i class="fa fa-angle-right"></i></span></a>
    </div>
<!-- #Slider Ends -->
</div>

src/Redes/SivelBundle/Resources/views/Template/informacion.html.twig
<!-- Cirlce Starts -->
<div id="about"  class="container spacer about">
<h2 class="text-center wowload fadeInUp">Sistema de Seguimiento a Iniciativas y Vinculaciones en la Economía Local </h2>  
  <div class="row">
  <div class="col-sm-6 wowload fadeInLeft">
    <h4><i class="fa fa-crosshairs"></i> Objetivo </h4>
    <p>A través de este sistema, administradores o promotores de redes de intercambio pueden gestionar toda la información de las actividades de los miembros de manera centralizada, así como manejar indicadores básicos para los procesos de Monitoreo y Evaluación.</p>
  </div>
  <div class="col-sm-6 wowload fadeInRight">
  <h4><i class="fa fa-dropbox"></i> Productos y servicios</h4>
  <p>Este modulo se utiliza para gestionar las categorías de los diversos tipos de productos y servicios presentes en la red de intercambio. A su vez, presenta un resumen de los negocios ofrecen o demandan cada categoría.</p>    
  </div>
  </div>

  <div class="services">
  <h3 class="text-center wowload fadeInUp">Servicios y productos que se ofrecen en la red</h3>
  <ul class="row text-center list-inline  wowload bounceInUp">
      <li>
            <span><i class="fa fa-pagelines"></i><b>Produccion agricola</b></span>
        </li>
        <li>
            <span><i class="fa fa-child"></i><b>Calzado</b></span>
        </li>
        <li>
            <span><i class="fa fa-cogs"></i><b>Construcción</b></span>
        </li>
        <li>
            <span><i class="fa fa-paw"></i><b>Ganado</b></span>
        </li>        
        <li>
            <span><i class="fa fa-anchor"></i><b>Pesca</b></span>
        </li>
    </ul>
  </div>
</div>
<!-- #Cirlce Ends -->

src/Redes/SivelBundle/Resources/views/Template/personas.html.twig
<!-- works -->
<div id="works"  class=" clearfix grid"> 
    
    {% for d in producto6 %}
        <figure class="effect-oscar  wowload fadeInUp">
            {% if d.img0Producto |length > 3 %}
                {%  set img = app.request.schemeAndHttpHost ~ '/' ~ d.img0Producto %}
            {% else %}
                {%  set img = asset('images/box_icon.png') %}
            {% endif %}
            <img src="{{ img }}" />
            <figcaption>
               <h2>{{ d.nombreProducto }}</h2>
               <p>{{ d.descripcionProducto }}<br>
                    <a href="{{ img }}" data-gallery>Expandir imagen</a><br>
                    <a href="" >Ver contacto</a>
               </p>            
            </figcaption>
        </figure>
    {% endfor %}
    {% for d in servicio6 %}
        <figure class="effect-oscar  wowload fadeInUp">
            {% if d.img0Servicio |length > 3 %}
                {%  set img = app.request.schemeAndHttpHost ~ '/' ~ d.img0Servicio %}
            {% else %}
                {%  set img = asset('images/servicios.jpg') %}
            {% endif %}
            <img src="{{ img }}" />
            <figcaption>
               <h2>{{ d.nombreServicio }}</h2>
               <p>{{ d.descripcionServicio }}<br>
                    <a href="{{ img }}" data-gallery>Expandir imagen</a><br>
                    <a href="" >Ver contacto</a>
               </p>            
            </figcaption>
        </figure>
    {% endfor %}

</div>
<!-- works -->